/**
 * 
 */
package com.craft.reviewable.controller;

import java.util.List;

import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.craft.reviewable.domain.Product;
import com.craft.reviewable.exception.ReviewableException;
import com.craft.reviewable.service.ProductService;
import com.craft.reviewable.validator.ProductValidator;

/**
 * @author Vignesh
 *
 */

@RestController
@RequestMapping("/v1.0/product")
public class ProductController {

	@Autowired
	private ProductService productService;

	@Autowired
	ProductValidator productValidator;

	public static final Logger LOGGER = LoggerFactory
			.getLogger(com.craft.reviewable.controller.ProductController.class);

	public ProductController(ProductService productService) {
		this.productService = productService;
	}

	/**
	 * Initiate validators for the Product entity
	 */
	@InitBinder
	protected void initBinder(WebDataBinder binder) {
		binder.setValidator(productValidator);
	}

	/**
	 * REST API to get all products
	 * 
	 * @return List of products
	 */
	@RequestMapping(path = "/all", method = RequestMethod.GET)
	public ResponseEntity<List<Product>> getAllProducts() {
		LOGGER.info("Executing GET API on /v1.0/product/all");
		return new ResponseEntity<>(productService.getAllProducts(), HttpStatus.OK);
	}

	/**
	 * REST API to get product by id
	 * 
	 * @param id
	 *            unique ID for the product
	 * @return The Product entity
	 * @throws ReviewableException
	 */
	@RequestMapping(path = "/{id}", method = RequestMethod.GET)
	public ResponseEntity<Product> getProductById(@PathVariable final String id) throws ReviewableException {
		LOGGER.info("Executing GET API on /v1.0/product/{id}");
		LOGGER.debug("Requested product ID: {}", id);
		try {
			return new ResponseEntity<>(productService.getProductById(id), HttpStatus.OK);
		} catch (ReviewableException ex) {
			LOGGER.info("Throwing the exception customized error");
			throw ex;
		}
	}

	/**
	 * REST API to create a product
	 * 
	 * @param product
	 *            The product entity
	 * @return The created product entity along with the unique ID generated by the
	 *         system
	 */
	@RequestMapping(method = RequestMethod.POST)
	public ResponseEntity<Product> createProduct(@Valid @RequestBody Product product) {
		LOGGER.info("Executing POST API on /v1.0/product");
		LOGGER.debug("Incoming Product details: {}", product);
		Product createdProduct = productService.createProduct(product);
		LOGGER.info("Product created successfully! Returning response to user");
		return new ResponseEntity<Product>(createdProduct, HttpStatus.CREATED);
	}
}
